"""'long'

Revision ID: 60bb8c455279
Revises: cb437351d6c3
Create Date: 2022-08-26 18:52:52.949690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60bb8c455279'
down_revision = 'cb437351d6c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('song_image', sa.Text(), nullable=True))
    op.add_column('recommendations', sa.Column('song_preview', sa.Text(), nullable=True))
    op.add_column('recommendations', sa.Column('song_url', sa.Text(), nullable=True))
    op.drop_column('recommendations', 'url')
    op.drop_column('recommendations', 'preview')
    op.drop_column('recommendations', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('image', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('recommendations', sa.Column('preview', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('recommendations', sa.Column('url', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.drop_column('recommendations', 'song_url')
    op.drop_column('recommendations', 'song_preview')
    op.drop_column('recommendations', 'song_image')
    # ### end Alembic commands ###
