"""'rating'

Revision ID: 85fc1ba9efe1
Revises: ffd7f4e3908a
Create Date: 2022-09-09 14:33:06.723675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85fc1ba9efe1'
down_revision = 'ffd7f4e3908a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('song_rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'song_rating')
    # ### end Alembic commands ###
