"""'hello'

Revision ID: cb437351d6c3
Revises: 
Create Date: 2022-08-26 18:11:55.906896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb437351d6c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('image', sa.String(length=40), nullable=True))
    op.add_column('recommendations', sa.Column('preview', sa.String(length=40), nullable=True))
    op.add_column('recommendations', sa.Column('url', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'url')
    op.drop_column('recommendations', 'preview')
    op.drop_column('recommendations', 'image')
    # ### end Alembic commands ###
